### ISSUE TITLE
USE CASE:  binary object has runtime dependencies on other binaries

### ISSUE THREAD

**Issue by kestewart** [swinslow/spdx-examples#13]
Application depends on having system libc (and probably other binaries) available in order to execute properly. 

For example - time 1.9 expects glibc to execute.

See illustration of dependency tree in:
https://drive.google.com/drive/u/0/folders/1Z364N234jrs36pjDT8xcS5hUGjRmMTN9

**Comment by kestewart** [comment]
Another reference example that's being used by OpenC2 is BlinkyHaHa as described in:
https://docs.google.com/document/d/1SJINJGVj6GBn498zmg_C2EjxsDuDcknjOuqa0JrKZ0o/edit

**Comment by swinslow** [comment]
will do a version of this for example4 -- example2 (hello world) but representing glibc as separate package, runtime dependency

**Comment by swinslow** [comment]
@kestewart I'm adding this in example4 via #14 -- thanks!
